export const DESCRIPTION_EDITOR_SCRIPT = [
  "function descriptionEditorValue(editor) {",
  "  const images = Array.prototype.slice.call(editor.querySelectorAll(\"img[data-token]\"));",
  "  const replacements = images.map(function (image) {",
  "    const span = document.createElement(\"span\");",
  "    span.textContent = image.getAttribute(\"data-token\") || \"\";",
  "    image.parentNode.replaceChild(span, image);",
  "    return { image: image, span: span };",
  "  });",
  "  const value = editor.innerText.replace(/\\n$/, \"\");",
  "  replacements.forEach(function (replacement) {",
  "    if (replacement.span.parentNode) replacement.span.parentNode.replaceChild(replacement.image, replacement.span);",
  "  });",
  "  return value;",
  "}",
  "function syncDescriptionEditor(editor) {",
  "  const form = editor.closest(\"form\");",
  "  const hidden = form ? form.querySelector(\"textarea[data-description-value]\") : null;",
  "  if (hidden) hidden.value = descriptionEditorValue(editor);",
  "}",
  "function descriptionEditorCaretOffset(editor) {",
  "  const selection = window.getSelection();",
  "  if (!selection || selection.rangeCount === 0) return null;",
  "  const range = selection.getRangeAt(0);",
  "  if (!editor.contains(range.startContainer)) return null;",
  "  const prefix = document.createRange();",
  "  prefix.selectNodeContents(editor);",
  "  prefix.setEnd(range.startContainer, range.startOffset);",
  "  return prefix.toString().length;",
  "}",
  "function restoreDescriptionEditorCaret(editor, offset) {",
  "  if (offset === null) return;",
  "  const walker = document.createTreeWalker(editor, NodeFilter.SHOW_TEXT);",
  "  let remaining = offset;",
  "  let node = null;",
  "  while (walker.nextNode()) {",
  "    node = walker.currentNode;",
  "    const length = (node.nodeValue || \"\").length;",
  "    if (remaining <= length) break;",
  "    remaining -= length;",
  "  }",
  "  if (!node) return;",
  "  const range = document.createRange();",
  "  range.setStart(node, Math.min(remaining, (node.nodeValue || \"\").length));",
  "  range.collapse(true);",
  "  const selection = window.getSelection();",
  "  if (!selection) return;",
  "  selection.removeAllRanges();",
  "  selection.addRange(range);",
  "}",
  "function linkifyDescriptionEditor(editor) {",
  "  const caretOffset = descriptionEditorCaretOffset(editor);",
  "  const walker = document.createTreeWalker(editor, NodeFilter.SHOW_TEXT);",
  "  const nodes = [];",
  "  while (walker.nextNode()) nodes.push(walker.currentNode);",
  "  nodes.forEach(function (node) {",
  "    if (!node.parentElement || node.parentElement.closest(\"a\")) return;",
  "    const text = node.nodeValue || \"\";",
  "    const pattern = /https?:\\/\\/[^\\s<>]+/g;",
  "    let match;",
  "    let cursor = 0;",
  "    const fragment = document.createDocumentFragment();",
  "    let changed = false;",
  "    while ((match = pattern.exec(text)) !== null) {",
  "      const raw = match[0];",
  "      const url = raw.replace(/[.,!?;:]+$/, \"\");",
  "      if (!url) continue;",
  "      if (match.index > cursor) fragment.appendChild(document.createTextNode(text.slice(cursor, match.index)));",
  "      const link = document.createElement(\"a\");",
  "      link.href = url;",
  "      link.textContent = url;",
  "      fragment.appendChild(link);",
  "      if (raw.length > url.length) fragment.appendChild(document.createTextNode(raw.slice(url.length)));",
  "      cursor = match.index + raw.length;",
  "      changed = true;",
  "    }",
  "    if (!changed) return;",
  "    if (cursor < text.length) fragment.appendChild(document.createTextNode(text.slice(cursor)));",
  "    node.parentNode.replaceChild(fragment, node);",
  "  });",
  "  renderDescriptionImages(editor);",
  "  restoreDescriptionEditorCaret(editor, caretOffset);",
  "}",
  "function initializeDescriptionEditors() {",
  "  document.querySelectorAll(\"[data-description-editor]\").forEach(function (editor) {",
  "    if (editor.dataset.descriptionEditorInitialized === \"true\") { syncDescriptionEditor(editor); return; }",
  "    editor.dataset.descriptionEditorInitialized = \"true\";",
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  "    editor.addEventListener(\"input\", function () { syncDescriptionEditor(editor); });",
  "    editor.addEventListener(\"click\", function (event) {",
  "      const link = event.target && event.target.closest ? event.target.closest(\"a\") : null;",
  "      if (!link || !editor.contains(link)) return;",
  "      event.preventDefault();",
  "      if (event.ctrlKey || event.metaKey) {",
  "        window.open(link.href, \"_blank\", \"noopener,noreferrer\");",
  "      } else {",
  "        window.location.assign(link.href);",
  "      }",
  "    });",
  "    editor.addEventListener(\"paste\", function (event) {",
  "      const imageFiles = descriptionImageFiles(event.clipboardData);",
  "      if (imageFiles.length > 0) {",
  "        event.preventDefault();",
  "        imageFiles.forEach(function (file) { uploadDescriptionEditorImage(editor, file); });",
  "        return;",
  "      }",
  "      const text = event.clipboardData ? event.clipboardData.getData(\"text/plain\") : \"\";",
  "      if (!text) return;",
  "      event.preventDefault();",
  "      document.execCommand(\"insertText\", false, text);",
  "      linkifyDescriptionEditor(editor);",
  "      syncDescriptionEditor(editor);",
  "    });",
  "    editor.addEventListener(\"dragover\", function (event) {",
  "      if (!descriptionHasFileDrag(event.dataTransfer)) return;",
  "      event.preventDefault();",
  "      if (event.dataTransfer) event.dataTransfer.dropEffect = \"copy\";",
  "    });",
  "    editor.addEventListener(\"drop\", function (event) {",
  "      const droppedFiles = descriptionDroppedFiles(event.dataTransfer);",
  "      if (droppedFiles.length === 0) return;",
  "      event.preventDefault();",
  "      const imageFiles = droppedFiles.filter(descriptionIsImageFile);",
  "      if (imageFiles.length === 0) { reportImageUploadFailure(); return; }",
  "      imageFiles.forEach(function (file) { uploadDescriptionEditorImage(editor, file); });",
  "    });",
  "  });",
  "}",
  "document.addEventListener(\"DOMContentLoaded\", initializeDescriptionEditors);",
  "document.addEventListener(\"htmx:load\", initializeDescriptionEditors);",
  "function descriptionImageType(file) {",
  "  const type = file && file.type ? String(file.type).toLowerCase() : \"\";",
  "  if (type === \"image/png\" || type === \"image/webp\" || type === \"image/jpeg\") return type;",
  "  const name = file && file.name ? String(file.name).toLowerCase() : \"\";",
  "  if (/\\.png$/.test(name)) return \"image/png\";",
  "  if (/\\.webp$/.test(name)) return \"image/webp\";",
  "  if (/\\.(jpe?g)$/.test(name)) return \"image/jpeg\";",
  "  return \"\";",
  "}",
  "function descriptionIsImageFile(file) {",
  "  return descriptionImageType(file) !== \"\";",
  "}",
  "function descriptionDroppedFiles(source) {",
  "  if (!source) return [];",
  "  const files = [];",
  "  const items = source.items ? Array.prototype.slice.call(source.items) : [];",
  "  items.forEach(function (item) {",
  "    if (!item || item.kind !== \"file\" || typeof item.getAsFile !== \"function\") return;",
  "    const file = item.getAsFile();",
  "    if (file) files.push(file);",
  "  });",
  "  const direct = source.files ? Array.prototype.slice.call(source.files) : [];",
  "  direct.forEach(function (file) { if (file && files.indexOf(file) === -1) files.push(file); });",
  "  return files;",
  "}",
  "function descriptionHasFileDrag(source) {",
  "  if (!source) return false;",
  "  if (source.types && Array.prototype.indexOf.call(source.types, \"Files\") !== -1) return true;",
  "  return descriptionDroppedFiles(source).length > 0;",
  "}",
  "function descriptionImageFiles(source) {",
  "  return descriptionDroppedFiles(source).filter(descriptionIsImageFile);",
  "}",
  "function renderDescriptionImages(editor) {",
  "  const walker = document.createTreeWalker(editor, NodeFilter.SHOW_TEXT);",
  "  const nodes = [];",
  "  while (walker.nextNode()) nodes.push(walker.currentNode);",
  "  const pattern = /\\/api\\/images\\/[0-9A-Za-z_-]+/g;",
  "  nodes.forEach(function (node) {",
  "    if (!node.parentElement || node.parentElement.closest(\"a\")) return;",
  "    const text = node.nodeValue || \"\";",
  "    pattern.lastIndex = 0;",
  "    if (!pattern.test(text)) return;",
  "    pattern.lastIndex = 0;",
  "    const fragment = document.createDocumentFragment();",
  "    let match;",
  "    let cursor = 0;",
  "    while ((match = pattern.exec(text)) !== null) {",
  "      if (match.index > cursor) fragment.appendChild(document.createTextNode(text.slice(cursor, match.index)));",
  "      const image = document.createElement(\"img\");",
  "      image.className = \"description-image\";",
  "      image.setAttribute(\"data-token\", match[0]);",
  "      image.src = match[0];",
  "      image.alt = \"\";",
  "      fragment.appendChild(image);",
  "      cursor = match.index + match[0].length;",
  "    }",
  "    if (cursor < text.length) fragment.appendChild(document.createTextNode(text.slice(cursor)));",
  "    node.parentNode.replaceChild(fragment, node);",
  "  });",
  "}",
  "function insertDescriptionImageToken(editor, token) {",
  "  editor.focus();",
  "  const selection = window.getSelection();",
  "  let inserted = false;",
  "  if (selection && selection.rangeCount > 0 && editor.contains(selection.anchorNode)) {",
  "    const range = selection.getRangeAt(0);",
  "    range.deleteContents();",
  "    const node = document.createTextNode(token);",
  "    range.insertNode(node);",
  "    range.setStartAfter(node);",
  "    range.collapse(true);",
  "    selection.removeAllRanges();",
  "    selection.addRange(range);",
  "    inserted = true;",
  "  }",
  "  if (!inserted) editor.appendChild(document.createTextNode(token));",
  "  renderDescriptionImages(editor);",
  "  syncDescriptionEditor(editor);",
  "}",
  "function resizeDescriptionImage(target, file) {",
  "  const contentType = descriptionImageType(file);",
  "  return new Promise(function (resolve, reject) {",
  "    if (!contentType) { reject(new Error(\"unsupported image type\")); return; }",
  "    const url = URL.createObjectURL(file);",
  "    const image = new Image();",
  "    image.onload = function () {",
  "      const maxWidth = target.clientWidth || image.naturalWidth;",
  "      const scale = Math.min(1, maxWidth / image.naturalWidth);",
  "      const width = Math.max(1, Math.round(image.naturalWidth * scale));",
  "      const height = Math.max(1, Math.round(image.naturalHeight * scale));",
  "      const canvas = document.createElement(\"canvas\");",
  "      canvas.width = width;",
  "      canvas.height = height;",
  "      const context = canvas.getContext(\"2d\");",
  "      context.drawImage(image, 0, 0, width, height);",
  "      URL.revokeObjectURL(url);",
  "      canvas.toBlob(function (blob) {",
  "        if (blob) resolve(blob); else reject(new Error(\"unable to encode image\"));",
  "      }, contentType, 0.92);",
  "    };",
  "    image.onerror = function () { URL.revokeObjectURL(url); reject(new Error(\"unable to decode image\")); };",
  "    image.src = url;",
  "  });",
  "}",
  "function uploadDescriptionImage(target, file) {",
  "  return resizeDescriptionImage(target, file).then(function (blob) {",
  "    const form = new FormData();",
  "    form.append(\"file\", blob, file.name || \"image\");",
  "    return fetch(\"/api/images\", { method: \"POST\", body: form });",
  "  }).then(function (response) {",
  "    if (!response.ok) throw new Error(\"image upload failed: \" + response.status);",
  "    return response.json();",
  "  }).then(function (image) {",
  "    return image.url || \"/api/images/\" + image.id;",
  "  });",
  "}",
  "function reportImageUploadFailure() {",
  "  window.alert(\"Image upload failed.\");",
  "}",
  "function uploadDescriptionEditorImage(editor, file) {",
  "  uploadDescriptionImage(editor, file).then(function (token) {",
  "    insertDescriptionImageToken(editor, token);",
  "  }).catch(reportImageUploadFailure);",
  "}",
  "function uploadComposerImage(textarea, file) {",
  "  uploadDescriptionImage(textarea, file).then(function (token) {",
  "    textarea.value = textarea.value ? textarea.value + \"\\n\" + token : token;",
  "    textarea.dispatchEvent(new Event(\"input\", { bubbles: true }));",
  "  }).catch(reportImageUploadFailure);",
  "}",
  "function initializeComposerImageDrop() {",
  "  document.querySelectorAll(\"textarea.ideas-composer__description\").forEach(function (textarea) {",
  "    if (textarea.dataset.imageDropInitialized === \"true\") return;",
  "    textarea.dataset.imageDropInitialized = \"true\";",
  "    textarea.addEventListener(\"paste\", function (event) {",
  "      const files = descriptionImageFiles(event.clipboardData);",
  "      if (files.length === 0) return;",
  "      event.preventDefault();",
  "      files.forEach(function (file) { uploadComposerImage(textarea, file); });",
  "    });",
  "    textarea.addEventListener(\"dragover\", function (event) {",
  "      if (!descriptionHasFileDrag(event.dataTransfer)) return;",
  "      event.preventDefault();",
  "      if (event.dataTransfer) event.dataTransfer.dropEffect = \"copy\";",
  "    });",
  "    textarea.addEventListener(\"drop\", function (event) {",
  "      const droppedFiles = descriptionDroppedFiles(event.dataTransfer);",
  "      if (droppedFiles.length === 0) return;",
  "      event.preventDefault();",
  "      const imageFiles = droppedFiles.filter(descriptionIsImageFile);",
  "      if (imageFiles.length === 0) { reportImageUploadFailure(); return; }",
  "      imageFiles.forEach(function (file) { uploadComposerImage(textarea, file); });",
  "    });",
  "  });",
  "}",
  "document.addEventListener(\"DOMContentLoaded\", initializeComposerImageDrop);",
  "document.addEventListener(\"htmx:load\", initializeComposerImageDrop);",
  "function taskFormDraftKey(form) {",
  "  if (form.getAttribute(\"data-task-form\") === \"new\") return null;",
  "  const action = form.getAttribute(\"action\") || \"\";",
  "  const match = action.match(/\\/tasks\\/([^/?#]+)/);",
  "  if (match) return \"siftq.task-draft:\" + decodeURIComponent(match[1]);",
  "  return null;",
  "}",
  "function removeTaskDraft(taskId) {",
  "  if (!taskId) return;",
  "  try { localStorage.removeItem(\"siftq.task-draft:\" + taskId); } catch (e) {}",
  "}",
  "function taskFormDraftVersion(form) {",
  "  const versionInput = form.querySelector(\"#task-version\");",
  "  if (!versionInput) return null;",
  "  const version = Number(versionInput.value);",
  "  return Number.isFinite(version) ? version : null;",
  "}",
  "function saveTaskFormDraft(form) {",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  const titleInput = form.querySelector('input[name=\"title\"]');",
  "  const hidden = form.querySelector(\"textarea[data-description-value]\");",
  "  const editor = form.querySelector(\"[data-description-editor]\");",
  "  const title = titleInput ? titleInput.value : \"\";",
  "  const description = hidden ? hidden.value : editor ? descriptionEditorValue(editor) : \"\";",
  "  const draft = { title: title, description: description, updatedAt: Date.now() };",
  "  const version = taskFormDraftVersion(form);",
  "  if (version !== null) draft.version = version;",
  "  try {",
  "    localStorage.setItem(key, JSON.stringify(draft));",
  "  } catch (e) {}",
  "}",
  "function scheduleTaskFormDraft(form) {",
  "  if (form._taskDraftTimer) clearTimeout(form._taskDraftTimer);",
  "  form._taskDraftTimer = setTimeout(function () { saveTaskFormDraft(form); }, 500);",
  "}",
  "function restoreTaskFormDraft(form) {",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  let raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  let draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  "  if (!draft || typeof draft.title !== \"string\" || typeof draft.description !== \"string\") return;",
  "  if (typeof draft.updatedAt === 'number' && Date.now() - draft.updatedAt >= 24 * 60 * 60 * 1000) {",
  "    try { localStorage.removeItem(key); } catch (e) {}",
  "    return;",
  "  }",
  "  if (typeof draft.version === 'number') {",
  "    const serverVersion = taskFormDraftVersion(form);",
  "    if (serverVersion !== null && serverVersion !== draft.version) {",
  "      try { localStorage.removeItem(key); } catch (e) {}",
  "      return;",
  "    }",
  "  }",
  "  const titleInput = form.querySelector('input[name=\"title\"]');",
  "  if (titleInput) titleInput.value = draft.title;",
  "  const editor = form.querySelector(\"[data-description-editor]\");",
  "  if (editor) {",
  "    editor.textContent = draft.description;",
  "    linkifyDescriptionEditor(editor);",
  "    syncDescriptionEditor(editor);",
  "  } else {",
  "    const hidden = form.querySelector(\"textarea[data-description-value]\");",
  "    if (hidden) hidden.value = draft.description;",
  "  }",
  "}",
  "function initializeTaskFormDrafts() {",
  "  document.querySelectorAll(\"form[data-task-form]\").forEach(function (form) {",
  "    if (form.dataset.taskDraftInitialized === \"true\") return;",
  "    form.dataset.taskDraftInitialized = \"true\";",
  "    restoreTaskFormDraft(form);",
  "    form.addEventListener(\"input\", function () { scheduleTaskFormDraft(form); });",
  "  });",
  "}",
  "function refreshTaskFormDraftVersion() {",
  "  const form = document.querySelector('form[data-task-form=\"edit\"]');",
  "  if (!form) return;",
  "  const version = taskFormDraftVersion(form);",
  "  if (version === null) return;",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  let raw;",
  "  try { raw = localStorage.getItem(key); } catch (e) { return; }",
  "  if (!raw) return;",
  "  let draft;",
  "  try { draft = JSON.parse(raw); } catch (e) { return; }",
  "  if (!draft || typeof draft.title !== \"string\" || typeof draft.description !== \"string\") return;",
  "  if (draft.version === version) return;",
  "  draft.version = version;",
  "  try { localStorage.setItem(key, JSON.stringify(draft)); } catch (e) {}",
  "}",
  "document.addEventListener(\"DOMContentLoaded\", initializeTaskFormDrafts);",
  "document.addEventListener(\"htmx:load\", initializeTaskFormDrafts);",
  "document.body.addEventListener(\"htmx:oobAfterSwap\", refreshTaskFormDraftVersion);",
  "document.body.addEventListener(\"htmx:afterSettle\", refreshTaskFormDraftVersion);",
  "document.body.addEventListener(\"htmx:afterRequest\", function (event) {",
  "  const detail = event.detail || {};",
  "  const xhr = detail.xhr;",
  "  const status = xhr ? xhr.status : 0;",
  "  if (status < 200 || status >= 300) return;",
  "  try { if (xhr && typeof xhr.getResponseHeader === \"function\" && !xhr.getResponseHeader(\"HX-Redirect\")) return; } catch (e) { return; }",
  "  const elt = detail.elt;",
  "  const form = elt && elt.closest ? elt.closest(\"form[data-task-form]\") : null;",
  "  if (!form) return;",
  "  if (form._taskDraftTimer) { clearTimeout(form._taskDraftTimer); form._taskDraftTimer = null; }",
  "  const key = taskFormDraftKey(form);",
  "  if (!key) return;",
  "  try { localStorage.removeItem(key); } catch (e) {}",
  "});",
  "document.addEventListener(\"submit\", function (event) {",
  "  const form = event.target;",
  "  if (!form || !form.matches || !form.matches('form[action=\"/logout\"]')) return;",
  "  try {",
  "    const remove = [];",
  "    for (let i = 0; i < localStorage.length; i += 1) {",
  "      const key = localStorage.key(i);",
  "      if (key && key.indexOf(\"siftq.task-draft:\") === 0) remove.push(key);",
  "    }",
  "    remove.forEach(function (key) { localStorage.removeItem(key); });",
  "  } catch (e) {}",
  "});",
].join("\n");
